# Generated by Django 4.2.3 on 2023-08-18 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususerdata',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must start with '0' followed by 9 digits.", regex='^0\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must start with '0' followed by 9 digits.", regex='^0\\d{9}$')]),
        ),
    ]
