# Generated by Django 4.2.3 on 2023-08-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofilemodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
