# Generated by Django 4.2.3 on 2023-08-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_shoppingcart_session_carts_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
