# Generated by Django 4.2.3 on 2023-08-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_anonymoususerdata'),
        ('orders', '0002_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='anonymous_user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.anonymoususerdata'),
        ),
    ]
