# Generated by Django 4.2.3 on 2023-08-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_anonymous_user_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='ordersitems',
            options={'verbose_name_plural': 'Orders Items'},
        ),
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
